### ISSUE TITLE
Choose which plugins to update via git

### ISSUE THREAD

**Issue by bhargavy** [pdclark/git-plugin-updates#19] opened 2013-10-31 11:40 UTC
Is it possible to choose which plugins to update via git ? 
i.e can I disable git updates for some plugins.

**Comment by pdclark** [comment] 2013-10-31 19:36
Right now you can disable updates on a plugin by removing the GIt repo URL from Plugin URI and Git URI headers. I do hope to add a user interface in `wp-admin` soon.

**Comment by pdclark** [comment] 2013-11-01 01:02
Closing as duplicate of #3

**Closed as completed by pdclark** 2013-11-01 01:02 UTC
Labels: duplicate
